trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!

  displayName: 'Run a one-line script'

- script: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'eu-west-2'
    awsCommand: 's3'
    awsSubCommand: 'mb'
    awsArguments: 's3://cf-for-cake-halab-info'
    
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'eu-west-2'
    bucketName: 'cf-for-cake-halab-info'
    sourceFolder: 'CloudFormation'
    globExpressions: 's3_bucket.yml'

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'eu-west-2'
    stackName: 'cf-for-cake-halab-info-stack'
    templateSource: 's3'
    s3BucketName: 'cf-for-cake-halab-info'
    s3ObjectKey: 's3_bucket.yml'