trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!

  displayName: 'Run a one-line script'

- script: |
    echo set env variables for aws cli
    export AWS_ACCESS_KEY_ID=$(AWS.AccessKeyID)
    export AWS_SECRET_ACCESS_KEY=$(AWS.SecretAccessKey)
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    aws --version
    export AWS_ACCESS_KEY_ID=$(AWS.AccessKeyID)
    export AWS_SECRET_ACCESS_KEY=$(AWS.SecretAccessKey)
    aws configure set aws_access_key_id $(AWS.AccessKeyID)
    aws configure set aws_secret_access_key $(AWS.SecretAccessKey)
    cd CloudFormation
    pwd
- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'eu-west-2'
    awsCommand: 's3'
    awsSubCommand: 'ls'
  displayName: 'Run a multi-line script'